default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nest_form_development

test:
  <<: *default
  database: nest_form_test

production:
  <<: *default
  database: nest_form_production
  username: nest_form
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
